name 'test-rec'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures test-rec'
long_description 'Installs/Configures test-rec'
version '0.1.0'
